spring:
  application:
    name: user-crud-api
  cache:
    type: simple

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  error:
    include-message: never
    include-stacktrace: never
